defaults:
  - _self_
  - dataset: omomo_test
  - guidance:
      - pelvis
  - model:
      - infbagel
  - sampler:
      - pelvis

exp_name: infbagel
train: false
load_state_dict: true
batch_size: 1
device: cuda:0
use_tensorboard: true
ckpt_interval: 10

w: 1

interp_s: 3

num_gpus: 1
num_workers: 4
scene_type: occ_temp
max_window_size: 16
start_type: stand

load_language: true
load_scene: true
use_pi: true
load_scene_goal: true
load_pelvis_goal: true
load_object_goal: true
auto_regre_num: 2

use_object_keypoints: false
use_random_frame_bps: false
add_object_voxel: true

guidance_weight: 1

temp_voxel_num: 3

# Sampling method: consistency -> consistency-model sampling; diffusion -> diffusion-model sampling
sample_type: consistency
# Whether to additionally save the .pkl under motion_params_922/ (for mesh recovery)
save_motion_params: true
save_results_json: true

ckpt_path: "../checkpoint/checkpoint.pth"

vis: false

exp_dir: ${oc.env:ROOT_DIR}/results/outputs

hydra:
  run:
    dir: ${exp_dir}